# --- BACKGROUND ---
# background {
#     monitor =
#     path = screenshot
#
#     blur_passes = 3
#     blur_size = 8
#
#     color = rgba(0, 0, 0, 0.5)
# }
background {
    monitor =
    path = ~/Pictures/Wallpapers/wallpaper.jpg


    blur_passes = 0
    blur_size = 0

    color = rgba(0, 0, 0, 0.3)
}

# --- BIG CLOCK ---
label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 1)
    font_size = 110
    font_family = sans-serif bold
    position = 0, 180
    halign = center
    valign = center
}

# --- RANDOM QUOTES ---
label {
    monitor =
    # This grabs a short quote and updates it every time you lock
    text = cmd[update:60000] fortune -s
 font_size = 16
color = rgba(255, 255, 255, 0.6)
    font_family = sans-serif
    position = 0, -300
    halign = center
    valign = center
}

# --- GREETING ---
label {
    monitor =
    text = Welcome back, juju
    color = rgba(205, 214, 244, 1)
    font_size = 20
    font_family = sans-serif font-weight-bold
    position = 0, -60
    halign = center
    valign = center
}

# --- PASSWORD BOX ---
input-field {
    monitor =
    size = 320, 55

    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3

    outer_color = rgba(255, 255, 255, 0.3)
    inner_color = rgba(0, 0, 0, 0.5)

    font_color = rgb(255, 255, 255)

    fade_on_empty = false
    placeholder_text = Enter Password...

    position = 0, -140
    halign = center
    valign = center
}
