# --- BACKGROUND ---
background {
    monitor =
    path = ~/Pictures/Wallpapers/wallpaper.jpg   # Your new wallpaper
    blur_passes = 2      # Slight blur so you can still see the image
    blur_size = 4
    color = rgba(0, 0, 0, 0.4) # Dark overlay to make text pop
}

# --- BIG CLOCK ---
label {
    monitor =
    text = $TIME
    color = rgba(205, 214, 244, 1)
    font_size = 90
    font_family = sans-serif font-weight-bold
    position = 0, 150
    halign = center
    valign = center
}


# --- RANDOM QUOTES ---
label {
    monitor =
    # This grabs a short quote and updates it every time you lock
    text = cmd[update:60000] fortune -s
    color = rgba(205, 214, 244, 0.7)
    font_size = 12
    font_family = sans-serif
    position = 0, -300
    halign = center
    valign = center
}

# --- GREETING ---
label {
    monitor =
    text = Welcome back, juju
    color = rgba(205, 214, 244, 1)
    font_size = 20
    font_family = sans-serif font-weight-bold
    position = 0, -60
    halign = center
    valign = center
}

# --- PASSWORD BOX ---
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    outer_color = rgba(cba6f7ff)
    inner_color = rgba(30, 30, 46, 0.6)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    placeholder_text = <i>Enter Password...</i>
    position = 0, -120
    halign = center
    valign = center
}
