# ===== MODULES =====
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/binds.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/decoration.conf
source = ~/.config/hypr/modules/monitor.conf

# ===== GENERAL =====
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2

    col.active_border = rgba(cba6f7ff)
    col.inactive_border = rgba(44475aff)
}


