# --- AUTOSTART ---

# Wallpaper daemon
exec-once = swww-daemon
exec-once = sleep 1 && ~/.config/hypr/random_wall.sh

# Core apps
exec-once = waybar
exec-once = nm-applet --indicator
exec-once = swaync
exec-once = hypridle
exec-once = hyprpaper
# wallpaper + dynamic theme
exec-once = ~/.config/hypr/random_wall.sh
