decoration {
    rounding = 12

    blur {
        enabled = yes
        size = 5
        passes = 2
    }
}
decoration {
    rounding = 12
}

general {
    border_size = 2
}
decoration {
    blur {
        enabled = yes
        size = 6
        passes = 2
    }
}
