input {
    kb_layout = us
    follow_mouse = 1

    sensitivity = -0.2
    accel_profile = adaptive

    touchpad {
        natural_scroll = true
        scroll_factor = 0.7

        # ✅ Enable taps
        tap-to-click = true

        # ✅ IMPORTANT: disable clickfinger (this fixes right click behavior)
        clickfinger_behavior = false

        # ✅ Tap mapping
        tap_button_map = lrm

        tap-and-drag = true
        drag_lock = false

        disable_while_typing = false
    }
}
# =========================
# macOS-like Gestures
# =========================
# =========================
# 3-Finger (Navigation)
# =========================

gesture = 3, left, workspace, scale: 2.0
gesture = 3, right, workspace, scale: 2.0
gesture = 3, up, fullscreen
gesture = 3, down, dispatcher, exec, rofi -show drun

# =========================
# 4-Finger (Power + Media)
# =========================

gesture = 4, up, dispatcher, exec, playerctl play-pause
gesture = 4, down, dispatcher, exec, playerctl next

gesture = 4, left, workspace, -1
gesture = 4, right, workspace, +1
