# --- KEYBINDS ---
$mainMod = SUPER

# Apps
bind = $mainMod, Q, killactive
bind = $mainMod, T, exec, kitty
bind = $mainMod, E, exec, dolphin
bind = $mainMod, V, exec, code
bind = $mainMod, B, exec, google-chrome
bind = $mainMod, A, exec, rofi -show drun

# System
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, P, exec, grim -g "$(slurp)" ~/Pictures/screenshot-$(date +%s).png

bind = $mainMod, slash, exec, cat ~/.config/hypr/cheatsheet.txt | rofi -dmenu -i -p "Shortcuts" -theme-str 'window {width: 600px;}'

bind = ALT, Control_R, exec, killall waybar; waybar &

bindl = , switch:on:Lid Switch, exec, pidof hyprlock || hyprlock

# Wallpaper + WiFi
bind = $mainMod ALT, W, exec, ~/.config/hypr/random_wall.sh
bind = $mainMod, W, exec, kitty --class floating_kitty -e nmtui

# Navigation
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Screenshot
bindl = , Print, exec, grim ~/Pictures/$(date +%Y-%m-%d_%H-%M-%S).png

# Volume
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Brightness
bindel = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
